title: Harin Lee
description: >-
  AKA. HarinWorks
show_downloads: false
google_analytics: ""
github:
  is_user_page: false
  is_project_page: false
lsi: true
profile: true
baseurl: ""
url: ""
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
exclude:
  - README.md
